name: unit testing and code coverage

on : 
<<<<<<< add-function
      pull_request  

jobs: 
    build:
=======
      pull request  

jobs: 
    build: 
    coverage:
>>>>>>> main
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:   
                node-version: 20
          - run: npm ci
          - run: npm test
          - uses: ArtiomTr/jest-coverage-report-action@v2